add Gluten check style (#222)
* add checkstyle script

* add checkstyle script

* update check style script

* failed when style check error

diff --git a/pipelines/aws/Gluten-CI/Jenkinsfile b/pipelines/aws/Gluten-CI/Jenkinsfile
--- a/pipelines/aws/Gluten-CI/Jenkinsfile
+++ b/pipelines/aws/Gluten-CI/Jenkinsfile
@@ -14,7 +14,7 @@ pipeline {
     }
 
     parameters {
-        string(name: 'branch', defaultValue: 'clickhouse_backend', description: 'gluten branch')
+        string(name: 'branch', defaultValue: '', description: 'gluten branch')
     }
 
 
@@ -35,6 +35,28 @@ pipeline {
                         script {
                             sh 'env'
                             githubCheckout 'gluten', 'main', 'https', 'github.com', '+refs/pull/*:refs/remotes/origin/pr/* +refs/heads/*:refs/remotes/origin/*', 'kyligencegit', 'oap-project'
+                        }
+                    }
+                }
+            }
+        }
+
+        stage("Code Style Check") {
+            steps {
+                container('git') {
+                    dir('clickhouse') {
+                        script {
+                            status = sh returnStatus: true ,script:'''
+                            info=`\${WORKSPACE}/clickhouse/utils/local-engine/tool/check-style`
+                            if [ -z "$info" ]; then
+                                echo "check success"
+                            else
+                                exit 1
+                            fi
+                            '''
+                            if (status == 1) {
+                                error("failed")
+                            }
                         }
                     }
                 }
